FROM deeplearnphysics/base:latest

MAINTAINER kterao@slac.stanford.edu

RUN pip --no-cache-dir --disable-pip-version-check install --upgrade tensorflow-gpu==1.12.0 && \
    pip --no-cache-dir --disable-pip-version-check install tensorboard && \
    pip --no-cache-dir --disable-pip-version-check install keras
	
