FROM deeplearnphysics/larcv2-docker:cuda9.0-cudnn7-ub16.04-root6.14.04

MAINTAINER kterao@slac.stanford.edu

RUN pip --no-cache-dir --disable-pip-version-check install torch==0.4.1 torchvision


    
	
